FROM node:alpine
WORKDIR /app

RUN npm config set unsafe-perm true
COPY package.json .
RUN npm i
RUN npm i react-scripts
# THIS copy is not nessosry,since using volume mapping
# But no harm to put, will definately need for
# production
COPY . .

CMD ["npm", "run", "start"]
